### ISSUE TITLE
OneStepCheckout compatibility

### ISSUE THREAD

**Issue by julianvdrielen** [tig-nl/buckaroo-magento2#32]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

---

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with the TIG Buckaroo Magento extension)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Buckaroo ticket [BUCK#F201831240].

This module is not compatible with OneStepCheckout.com. Errors do occur when loading the page, we're also unable to compleet an order.

Issues:
* Field validation on page load. (All fields show "This is a required field"
* After selecting shipping method the checkout gets stuck on an infinite loop with XHR requests

These issues should be easily reproducable. In case more information is needed.
Please contact Buckaroo with the internal ticket number.

### TIG supportdesk

On Github we will respond in English even when the question was asked in Dutch.

**Comment by tig-jaspersmits** [comment]
Good morning Julian,

Thank you for submitting this. We are aware that those extensions aren't compatible with each other. Just discussed this with Buckaroo and we will start working on this compatibility next sprint. If you want i can subscribe you to our release notes, this way you will get informed once the new version gets released. If you want to share your email address i can add you, or you can subscribe on this page: https://confluence.tig.nl/x/v4SC

Kind regards,

Jasper
TIG

**Comment by julianvdrielen** [comment]
Morning Jasper,

Please notify me on updates at julian@cream.nl.
Is there any ETA on when this next sprint will happen?

Kind regards,
Julian
Cream

**Comment by tig-jaspersmits** [comment]
Hi Julian,

Just added your address, so you should receive a mail once the release notes get updated.
The sprint start on 11 sept and runs for 2 weeks. It could be that an official release could take a bit longer.

Kind regards,

Jasper
TIG

**Comment by julianvdrielen** [comment]
Hi @tig-jaspersmits 
What is the status on this issue?

Did the past sprint succeed and include this issue?

Please consider this high priority.

Kind regards,
Julian
Cream

**Comment by tdgroot** [comment]
Also had issues with Buckaroo/Onestepcheckout integration. 

Selecting a bank/card/bicnumber doesn't update the view. I fixed it for my current project, but it'd be nice if Buckaroo supports Onestepcheckout out of the box.

If anyone is interested in my patch, please let me know.

**Comment by JosKalter** [comment]
Hi @tig-jaspersmits can you give us an update on this issue? 

Kind regards,
Jos

**Comment by tig-jaspersmits** [comment]
Hi @JosKalter,

Version 1.7.3. is released, i will update the release notes later this morning. But as far as compatibility goes for OSC, no full release for this yet. We are still working on it.

Kind regards,

Jasper
TIG

**Comment by tig-robertgrundeken** [comment]
@julianvdrielen @tdgroot @JosKalter We are still working on this. Because we worked quite some time on this and had some progress, but it is not fixed yet. 

We identified three problems:
+ All fields are validated on load of the checkout.
+ The general iDEAL radiobutton needs to be clicked sometimes twice to make the "place order" button available. 
+ Payment methods with fields extra fields in the checkout (like Afterpay, Payment Guaranty) can invoke an update-loop.  

The first two problems we could address with the help of @tdgroot example fix, and trying to put the logic from the mixin directly into the javascript of the extension. 
The third problem is that we need to validate the fields we added to the checkout as well as the rest of the checkout field. Which somehow triggers Idev's OSC to also triggers the ajax-update call. And end up in a update loop. Removing the [additionalValidators.validate();](https://github.com/tig-nl/buckaroo-magento2/blob/master/view/frontend/web/js/view/payment/method-renderer/afterpay.js#L381) stops the loop, but will not validate the rest of the form, and could keep the "place order" button greyed out. 

We keep on working on it. Today I made [V1.7.4-RC1](https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.7.4-RC1) without solutions for this. Thanks for understanding.

**Comment by JosKalter** [comment]
Hi @tig-robertgrundeken any progress on this issue?

**Comment by tig-robertgrundeken** [comment]
@JosKalter in short: we tried several solutions, but none of them had the outcome we hoped for.

We need to rewrite the validate functionality to be compatible with OSC. We will put this on the worklog. On the side we are working on supporting magento's new releases, and have an improvements update. After that the focus will be on making this functional for new magento versions.

**Comment by renehol** [comment]
Hi @tig-robertgrundeken, how far along are you with the One Step Checkout integration?

**Comment by tig-robertgrundeken** [comment]
Hi @renehol thanks for pinging on this subject. There are some small steps taken, but there needs to be a lot of refactoring. I can't give you any dates.

Have you made any changes locally to fix certain problems?

**Comment by tig-jaspersmits** [comment]
Because of a clean-up action we will close this ticket. The ticket has been on our backlog and is still open. This indicates that we will work on it in the future or once Buckaroo decides to give priority to this compatibility.

**Comment by julianvdrielen** [comment]
A closed issue indicates a resolved ticket. This is not the case, it has been more than a year and this issue is still present, why is this taking so long and why is this not prioritised by Buckaroo?

**Comment by tig-jaspersmits** [comment]
@julianvdrielen this ticket should remain open. Closed the wrong one. But to answer your question about why it is taking so long. The only answer I currently have is that Buckaroo has given priority to other features and fixes over OSC compatibility.
